name: library_management
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_svg: 0.15.0
  googleapis_auth: 0.2.11+1
  http:
  speech_to_text: 0.7.2
  rxdart: 0.23.1
  page_transition: 1.1.5
  firebase_auth: 0.15.3+1
  stripe_payment: 1.0.6
  fluttertoast: 3.1.3
  barcode_scan:
  flutter:
    sdk: flutter
  flutter_screenutil: ^1.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway Extra Light
      fonts:
        - asset: fonts/Raleway/Raleway-ExtraLight.ttf
        - asset: fonts/Raleway/Raleway-ExtraLightItalic.ttf
          style: italic
    - family: Raleway Light
      fonts:
        - asset: fonts/Raleway/Raleway-Light.ttf
        - asset: fonts/Raleway/Raleway-LightItalic.ttf
          style: italic
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/Raleway-Regular.ttf
        - asset: fonts/Raleway/Raleway-Italic.ttf
          style: italic
    - family: Raleway Thin
      fonts:
        - asset: fonts/Raleway/Raleway-Thin.ttf
        - asset: fonts/Raleway/Raleway-ThinItalic.ttf
          style: italic
    - family: Raleway Medium
      fonts:
        - asset: fonts/Raleway/Raleway-Medium.ttf
        - asset: fonts/Raleway/Raleway-MediumItalic.ttf
          style: italic
    - family: Raleway Semi Bold
      fonts:
        - asset: fonts/Raleway/Raleway-SemiBold.ttf
        - asset: fonts/Raleway/Raleway-SemiBoldItalic.ttf
          style: italic
    - family: Raleway Bold
      fonts:
        - asset: fonts/Raleway/Raleway-Bold.ttf
        - asset: fonts/Raleway/Raleway-BoldItalic.ttf
          style: italic
    - family: Ubuntu Light
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-Light.ttf
        - asset: fonts/Ubuntu/Ubuntu-LightItalic.ttf
          style: italic
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu/Ubuntu-RegularItalic.ttf
          style: italic
    - family: Ubuntu Medium
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-Medium.ttf
        - asset: fonts/Ubuntu/Ubuntu-MediumItalic.ttf
          style: italic
    - family: Ubuntu Bold
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-Bold.ttf
        - asset: fonts/Ubuntu/Ubuntu-BoldItalic.ttf
          style: italic
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
